function getOutputMode(){return $("outputMode")?.value==="ledger"?"ledger":"blueprint"}
function isDemoBuild(){return document.body?.dataset?.demo==="1"}
function applyDemoBuildIfFlagged(){if(!isDemoBuild())return;const cap=Number(document.body.dataset.demoMaxSteps||"30")||30;const sl=$("stepsSlider");if(sl){sl.max=String(cap);sl.value=String(Math.min(Number(sl.value)||cap,cap));sl.dispatchEvent(new Event("input",{bubbles:!0}))}const ms=$("loopMaxSteps");if(ms){ms.max=String(cap);ms.value=String(Math.min(Number(ms.value)||cap,cap));ms.dispatchEvent(new Event("change",{bubbles:!0}))}qsa(".round-preset").forEach(b=>{const r=Number(b.dataset.round||0);if(r>cap)b.classList.add("hidden")});qsa("details.manual-panel, details.advanced").forEach(d=>d.classList.add("hidden"));try{setRoundLimit(cap,"demo-cap")}catch{}log(`demo build active: round cap=${cap}`)}
function getEvidencePayload(){return ($("evidencePayload")?.value||"").trim()}
function applyOutputModeUi(){const t=getOutputMode(),e=getLang(),n=I18N[e]||I18N.vi,a=$("evidencePayload"),o=$("modeHint");a&&a.classList.toggle("hidden","ledger"!==t),o&&(o.textContent="ledger"===t?n.modeHintLedger:n.modeHintBlueprint);applyIntentUi()}
function applyIntentUi(){const i=getIntent(),e=getLang(),n=I18N[e]||I18N.vi,h=$("intentHint");if(!h)return;const map={auto:n.intentHintAuto,business:n.intentHintBusiness,learning:n.intentHintLearning,code:n.intentHintCode};h.textContent=map[i]||map.auto}
function buildFinalMarkdown(t,e=getLang(),n={}){const a=(new Date).toISOString(),o=$("stopPhrase")?.value||defaultStopPhrase(e),i=n.finalizationMode||(t.content.includes(o)?"confirmed":"draft_forced"),r=n.stopReason||lastStopReason||"unknown";return"en"===e?`# VS Brain Final Unified Report\n\n- Saved: ${a}\n- Provider: ${t.platform}\n- Source title: ${t.title||""}\n- URL: ${t.url||""}\n- Stop phrase: ${o}\n- Final agreement detected: ${t.content.includes(o)?"yes":"no"}\n- Finalization mode: ${i}\n- Stop reason: ${r}\n\n## 1. Final conclusion\n\nThe debate session reached the latest available final response below. Treat it as the current unified answer unless remaining risks are listed inside the content.\n\n## 2. Unified final answer\n\n${t.content}\n\n## 3. Resolved critique points\n\nExtract from the final answer above: issues marked fixed, accepted, or no longer blocking.\n\n## 4. Remaining assumptions / limits\n\nIf the final answer contains assumptions, constraints, or unresolved risks, review them before execution.\n\n## 5. Next actions\n\nUse the final answer as the execution-ready baseline. If implementation is required, convert it into tasks/checklist.\n\n## 6. Audit trail\n\nGenerated by VS Brain ${VS_BRAIN_RUNTIME_VERSION} from the latest provider response.\n`:`# VS Brain - Báo cáo thống nhất cuối\n\n- Lưu lúc: ${a}\n- Provider: ${t.platform}\n- Tiêu đề nguồn: ${t.title||""}\n- URL: ${t.url||""}\n- Cụm chốt: ${o}\n- Đã phát hiện đồng thuận cuối: ${t.content.includes(o)?"có":"không"}\n- Chế độ chốt: ${i}\n- Lý do dừng: ${r}\n\n## 1. Kết luận cuối cùng\n\nPhiên phản biện đã lấy phản hồi mới nhất bên dưới làm bản thống nhất hiện tại. Chỉ coi là sẵn sàng thực thi nếu phần nội dung không còn liệt kê rủi ro chặn.\n\n## 2. Bản trả lời thống nhất\n\n${t.content}\n\n## 3. Các điểm phản biện đã được xử lý\n\nTrích từ bản cuối ở trên: các lỗi đã được sửa, các phản biện đã được hấp thụ, hoặc các điểm không còn là blocker.\n\n## 4. Giả định / giới hạn còn lại\n\nNếu bản cuối còn nêu giả định, ràng buộc, hoặc rủi ro chưa xử lý, cần kiểm tra trước khi triển khai.\n\n## 5. Việc cần làm tiếp theo\n\nDùng bản thống nhất làm baseline thực thi. Nếu cần triển khai, chuyển thành task/checklist cụ thể.\n\n## 6. Audit trail\n\nTạo bởi VS Brain ${VS_BRAIN_RUNTIME_VERSION} từ phản hồi mới nhất của provider.\n`}
function buildFinalJson(t,e=getLang(),n={}){const a=$("stopPhrase")?.value||defaultStopPhrase(e),o=t.content.includes(a),i=n.finalizationMode||(o?"confirmed":"draft_forced"),r=n.stopReason||lastStopReason||"unknown";return JSON.stringify({app:"VS Brain",version:VS_BRAIN_RUNTIME_VERSION,language:e,saved_at:(new Date).toISOString(),provider:t.platform,title:t.title,url:t.url,stop_phrase:a,final_agreement:o,finalization_mode:i,stop_reason:r,require_final_confirm:!0,final_report_schema:"vs-brain.final_report.v1",sections:{final_conclusion:"en"===e?"Latest provider response is saved as current unified answer.":"Phản hồi mới nhất được lưu làm bản thống nhất hiện tại.",unified_final_answer:t.content,resolved_critique_points:[],remaining_assumptions_or_limits:[],next_actions:[]},raw_final_content:t.content},null,2)}
async function finalizeAndSave(){return await __vsbrainFinalizeAndSaveInner()}
async function loadRecoveredLoopState(){return window.__vsbrainRecovery?window.__vsbrainRecovery.loadCheckpoint():null}
async function clearRecoveredLoopState(){return window.__vsbrainRecovery?window.__vsbrainRecovery.clearCheckpoint():null}
async function tryRestoreRecoveredState(){const t=await loadRecoveredLoopState();if(!t?.sessionId||"running"!==t.status)return;await clearRecoveredLoopState().catch(()=>{});log(`recovery: discarded interrupted session=${t.sessionId} step=${t.step||0}/${t.maxSteps||0}; ready for fresh Start`);setStatus("Ready","ready")}
function setRoundLimit(t,e="manual"){const n=$("stepsSlider"),a=$("loopMaxSteps"),o=$("sliderValue"),i=loopState?loopState.step:0;let r=Math.max(1,Math.min(1000,Number(t)||1));loopState&&r<i&&(r=loopState.maxSteps,log(`cannot reduce below current round: ${i}`)),a&&(a.value=String(r)),n&&(n.value=String(r)),o&&(o.textContent=String(r)),loopState&&(loopState.maxSteps=r),$("loopCounter")&&($("loopCounter").textContent=`${i}/${r}`),qsa(".round-preset").forEach(t=>t.classList.toggle("active",Number(t.dataset.round)===r)),"slider"!==e&&log(`round limit set=${r} (${e})`)}

// === Termination Envelope Protocol v0.8.68 ===
// Enhanced parser: overrides runtime-recovery.js stub with nonce validation support
const TERMINATION_ENVELOPE_RE = /```vsbrain-termination\s*\n?([\s\S]*?)```/g;
function parseTerminationEnvelope(text, expectedNonce) {
  const src = String(text || '');
  const matches = [...src.matchAll(TERMINATION_ENVELOPE_RE)];
  if (matches.length === 0) return { ok: false, code: 'ERR_TERMINATION_ENVELOPE_MISSING' };
  if (matches.length > 1) return { ok: false, code: 'ERR_TERMINATION_ENVELOPE_MULTIPLE' };
  const body = matches[0][1].trim();
  // JSON-first parse
  let parsed = null;
  try {
    parsed = JSON.parse(body);
    if (typeof parsed !== 'object' || Array.isArray(parsed) || parsed === null) parsed = null;
  } catch(e) {
    // Fallback: key-value line parser
    const kv = {};
    for (const line of body.split(/\r?\n/)) {
      const m = line.match(/^([a-zA-Z_0-9]+)\s*:\s*(.+)$/);
      if (!m) continue;
      kv[m[1].trim()] = m[2].trim();
    }
    if (Object.keys(kv).length >= 2) parsed = kv;
  }
  if (!parsed) return { ok: false, code: 'ERR_PARSE_NO_VALID_CONTENT', raw: body };
  // Validate required fields
  const req = ['status', 'session_nonce', 'should_continue', 'critical_remaining'];
  for (const k of req) {
    if (!(k in parsed)) return { ok: false, code: 'ERR_TERMINATION_FIELD_' + k.toUpperCase() + '_MISSING', fields: parsed };
  }
  const norm = {
    status: String(parsed.status || '').toLowerCase().trim(),
    session_nonce: String(parsed.session_nonce || '').trim(),
    should_continue: parsed.should_continue === true || String(parsed.should_continue).toLowerCase() === 'true' || parsed.should_continue === 1,
    critical_remaining: parsed.critical_remaining === true || String(parsed.critical_remaining).toLowerCase() === 'true' || parsed.critical_remaining === 1,
    raw: body,
    fields: parsed,
    parser: typeof parsed === 'object' && !Array.isArray(parsed) && 'status' in parsed && 'session_nonce' in parsed ? 'json' : 'key-value'
  };
  // Semantic validation
  if (norm.status !== 'ready_to_finalize') return { ok: false, code: 'ERR_TERMINATION_STATUS_INVALID', fields: parsed };
  if (norm.should_continue !== false) return { ok: false, code: 'ERR_TERMINATION_SHOULD_CONTINUE_TRUE', fields: parsed };
  if (norm.critical_remaining !== false) return { ok: false, code: 'ERR_TERMINATION_CRITICAL_REMAINING_TRUE', fields: parsed };
  if (!norm.session_nonce) return { ok: false, code: 'ERR_TERMINATION_NONCE_EMPTY', fields: parsed };
  // Optional nonce validation
  if (expectedNonce && norm.session_nonce !== expectedNonce) {
    return { ok: false, code: 'ERR_TERMINATION_NONCE_MISMATCH', expected: expectedNonce, got: norm.session_nonce, fields: parsed };
  }
  return { ok: true, code: 'PARSED', envelope: norm };
}
// Override runtime-recovery.js stub with enhanced version
if (window.__vsbrainRecovery) {
  window.__vsbrainRecovery.parseTerminationEnvelope = parseTerminationEnvelope;
}