// VS Brain page helpers — content-script bundle.
// All functions referenced by popup.js via chrome.scripting.executeScript({func:...})
// must live here so they execute in the page context with their dependencies resolved.
//
// Why this file exists: chrome.scripting.executeScript({func: foo}) only injects foo's
// own source; any other helper foo() calls must already exist in the target tab. The
// previous architecture stored these helpers inside popup.js (extension page only),
// so executions in real ChatGPT/Gemini tabs threw ReferenceError silently and forced
// every preflight + finalize through slow fallback paths.
//
// This bundle is registered as a content_script in manifest.json for all certified
// AI sites + the developer mock lab (127.0.0.1).
(function(){
  if (window.__vsbrainPageHelpers) return; // idempotent
  const AI_HOSTS=[["chatgpt",["chatgpt.com","chat.openai.com","chat.openai.chatgpt.com"]],["gemini",["gemini.google.com"]],["claude",["claude.ai"]],["deepseek",["chat.deepseek.com","deepseek.com","platform.deepseek.com"]],["perplexity",["perplexity.ai"]],["grok",["grok.com","x.com/i/grok"]]];
  // Resolver: prefer page-injected helper (mock-provider in lab, native page in real sites)
  // otherwise fall back to the bundle's local definition. Lets developer mocks override
  // selectors without forking page-helpers.js.
  function __resolveHelper(name, localFn){
    const w = (typeof window !== "undefined") ? window[name] : null;
    return (typeof w === "function") ? w : localFn;
  }

  function extractQualitySignals(t){const e=String(t||""),n=e.toLowerCase(),a=n.match(/confidence\s*[:：]?\s*(\d+(?:\.\d+)?)/i)||n.match(/điểm tin cậy\s*[:：]?\s*(\d+(?:\.\d+)?)/i);return{confidence:a?Math.max(0,Math.min(10,Number(a[1]))):null,shouldContinue:/should_continue\s*[:：]?\s*true/i.test(e)||/tiếp tục\s*[:：]?\s*(có|true)/i.test(n),noNewIssues:/(no new issues|không có lỗi mới|không còn lỗi mới|no material issues)/i.test(e),contradiction:/(contradiction|mâu thuẫn|inconsistent|không nhất quán)/i.test(e),critical:/(critical issues?\s*[:：]\s*(?!none|không)|lỗi nghiêm trọng\s*[:：]\s*(?!không)|blockers?\s*[:：]\s*(?!none|không)|chặn\s*[:：]\s*(?!không))/i.test(e)}}

  function providerFromUrl(t=""){const e=String(t||"").toLowerCase();if(/127\.0\.0\.1:\d+\/lab\/mock-chatgpt\.html/i.test(e))return"chatgpt";if(/127\.0\.0\.1:\d+\/lab\/mock-gemini\.html/i.test(e))return"gemini";if(e.includes("chatgpt.com")||e.includes("chat.openai.com")||e.includes("chat.openai.chatgpt.com"))return"chatgpt";if(e.includes("gemini.google.com/app"))return"gemini";for(const[t,n]of AI_HOSTS)if(n.some(t=>e.includes(String(t).toLowerCase())))return t;return"unknown"}

  function extractLatestResponseInPage(t="latest"){function e(t){return(t||"").replace(/\r\n/g,"\n").replace(/[ \t]+$/gm,"").replace(/\n{3,}/g,"\n\n").trim()}function n(t){const e=t?.getBoundingClientRect?.();return!!e&&e.width>0&&e.height>0}function a(t){const a=e(t?.innerText||t?.textContent||"");if(!a||a.length<20)return!1;const o=(t?.tagName||"")+" "+(t?.className||"")+" "+(t?.getAttribute?.("data-testid")||"")+" "+(t?.getAttribute?.("aria-label")||"");return!(/textarea|composer|prompt|input/i.test(o))&&n(t)}function o(t){const e=String(t||location.href||location.hostname||"").toLowerCase(),n=location.hostname.toLowerCase();return/127\.0\.0\.1:\d+\/lab\/mock-gemini\.html/i.test(e)?"gemini":/127\.0\.0\.1:\d+\/lab\/mock-chatgpt\.html/i.test(e)?"chatgpt":e.includes("gemini.google.com/app")||n==="gemini.google.com"?"gemini":e.includes("chatgpt.com")||e.includes("chat.openai.com")||e.includes("chat.openai.chatgpt.com")||n.includes("chatgpt.com")?"chatgpt":providerFromUrl(e)}if("selection"===t){const t=e(String(window.getSelection?.()||""));if(t)return{platform:"selection",title:document.title,url:location.href,content:t}}const i=location.hostname,r=o(location.href),s="chatgpt"===r?['[data-message-author-role="assistant"]','[data-testid^="conversation-turn-"] [class*="markdown"]','[data-testid^="conversation-turn-"] .markdown','main [data-message-author-role="assistant"]','article .markdown',"article",".markdown"]:"gemini"===r?['model-response','message-content','.model-response-text','main .markdown','article','.markdown']:i.includes("deepseek.com")?[".ds-markdown",'[class*="message"]','[class*="answer"]']:i.includes("claude.ai")?['[data-testid*="assistant"]',".font-claude-message",'[class*="assistant"]']:i.includes("perplexity.ai")?['[data-testid*="answer"]',".prose",'[class*="answer"]']:["main article",".markdown","p"];let c=[];for(const t of s)c.push(...Array.from(document.querySelectorAll(t)));c=c.filter(a);const l=c.map(t=>e(t.innerText||t.textContent||"")).filter(t=>t&&t.length>30).filter((t,e,n)=>n.indexOf(t)===e);let u=l[l.length-1]||"";if(!u&&"chatgpt"===r){const t=Array.from(document.querySelectorAll('[data-message-author-role="assistant"]')).filter(a);u=e(t[t.length-1]?.innerText||t[t.length-1]?.textContent||"")}if(!u&&"chatgpt"===r){const t=e(document.body?.innerText||"");const n=t.split(/\n{2,}|\n(?=(?:OK|TEST_SEED_|Kết luận|Verdict|PASS|PARTIAL|FAIL)\b)/).map(e).filter(t=>t.length>30&&!/^(ChatGPT|New chat|Đoạn chat mới|Search|Tìm kiếm|Log in|Sign up)/i.test(t));u=n[n.length-1]||""}if(!u&&"gemini"===r){const t=Array.from(document.querySelectorAll('message-content, model-response, article, .markdown')).filter(a);u=e(t[t.length-1]?.innerText||t[t.length-1]?.textContent||"")}return{platform:r,title:document.title,url:location.href,content:u}}

  async function clickSendInPage(){const t=['button[data-testid="send-button"]','button[data-testid*="send" i]','button[aria-label*="Send" i]','button[aria-label*="Gửi" i]','button[aria-label*="Submit" i]','button[aria-label*="Run" i]','button[aria-label*="send message" i]',"button.send-button","button:has(mat-icon)","button"];await new Promise(t=>setTimeout(t,250));for(const e of t){let n=[];try{n=Array.from(document.querySelectorAll(e))}catch(t){continue}n=n.filter(t=>{const e=`${t.innerText||""} ${t.getAttribute("aria-label")||""} ${t.getAttribute("data-testid")||""}`.toLowerCase(),n=t.getBoundingClientRect?.();return n&&n.width>0&&n.height>0&&!t.disabled&&(e.includes("send")||e.includes("gửi")||e.includes("submit")||e.includes("arrow")||e.includes("send-button"))});const a=n[n.length-1];if(a)return a.click(),{ok:!0,selector:e}}const e=document.activeElement||document.querySelector('textarea,[contenteditable="true"],[role="textbox"]');if(e){try{return e.dispatchEvent(new KeyboardEvent("keydown",{bubbles:!0,key:"Enter",code:"Enter"})),e.dispatchEvent(new KeyboardEvent("keypress",{bubbles:!0,key:"Enter",code:"Enter"})),e.dispatchEvent(new KeyboardEvent("keyup",{bubbles:!0,key:"Enter",code:"Enter"})),{ok:!0,selector:"keyboard:Enter"}}catch(t){}try{return e.dispatchEvent(new KeyboardEvent("keydown",{bubbles:!0,key:"Enter",code:"Enter",ctrlKey:!0})),e.dispatchEvent(new KeyboardEvent("keyup",{bubbles:!0,key:"Enter",code:"Enter",ctrlKey:!0})),{ok:!0,selector:"keyboard:Ctrl+Enter"}}catch(t){}}return{ok:!1,error:"Không tìm thấy nút gửi"}}

  async function fillPromptInPage(t,e=!1){const n=t=>new Promise(e=>setTimeout(e,t));function a(t){const e=t.getBoundingClientRect?.();return!!e&&e.width>0&&e.height>0}async function o(t,e){try{t.focus(),t.click(),await navigator.clipboard.writeText(e);const a=document.execCommand?.("paste");return t.dispatchEvent(new InputEvent("input",{bubbles:!0,inputType:"insertFromPaste",data:e})),await n(80),a||(t.innerText||t.value||"").includes(e.slice(0,40))}catch(t){return!1}}function i(t,e){if(t.scrollIntoView?.({block:"center"}),t.focus(),t.click(),t.isContentEditable||"true"===t.getAttribute("contenteditable")||"textbox"===t.getAttribute("role"))return t.textContent="",t.dispatchEvent(new InputEvent("input",{bubbles:!0,inputType:"deleteContentBackward"})),t.textContent=e,t.dispatchEvent(new InputEvent("input",{bubbles:!0,inputType:"insertText",data:e})),t.dispatchEvent(new KeyboardEvent("keyup",{bubbles:!0,key:" "})),(t.innerText||t.textContent||"").includes(e.slice(0,40));if("value"in t){const n="TEXTAREA"===t.tagName?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,a=Object.getOwnPropertyDescriptor(n,"value");return a?.set?.call(t,e),t.dispatchEvent(new Event("input",{bubbles:!0})),t.dispatchEvent(new Event("change",{bubbles:!0})),(t.value||"").includes(e.slice(0,40))}return!1}const r=["rich-textarea .ql-editor",'.ql-editor[contenteditable="true"]','div[contenteditable="true"][role="textbox"]','div[contenteditable="true"][data-testid*="prompt" i]','div[contenteditable="true"][aria-label*="message" i]','div[contenteditable="true"][aria-label*="Message" i]','div[contenteditable="true"]',"textarea[placeholder]","textarea",'[role="textbox"]',"div.ProseMirror",'[data-testid*="composer"] [contenteditable="true"]'];for(let e=0;e<3;e++){for(const e of r){const n=Array.from(document.querySelectorAll(e)).filter(t=>!t.disabled&&a(t)),r=n[n.length-1];if(r){if(i(r,t))return{ok:!0,method:"setValue",selector:e};if(await o(r,t))return{ok:!0,method:"clipboard",selector:e}}}await n(250)}return{ok:!1,error:"Không tìm thấy hoặc không set được ô nhập chat. Hãy click vào ô chat Gemini rồi thử lại."}}

  function pageScanner(){const t=location.href,e=location.hostname,n=((t=>"unknown"===t?"":t)(providerFromUrl(t)))||(/127\.0\.0\.1:\d+\/lab\/mock-gemini\.html/i.test(t)?"gemini":/127\.0\.0\.1:\d+\/lab\/mock-chatgpt\.html/i.test(t)?"chatgpt":e.includes("gemini.google.com/app")?"gemini":e.includes("chatgpt.com")||e.includes("chat.openai.com")||e.includes("chat.openai.chatgpt.com")?"chatgpt":providerFromUrl(e)),a=document.title.replace(/\s*[|-]\s*(ChatGPT|Gemini).*$/i,"").trim()||document.title||"Untitled",o=n+":"+(location.pathname||"/").replace(/[^a-z0-9_-]+/gi,"_").replace(/^_+|_+$/g,"")||"current";let i=[];"chatgpt"===n?i=Array.from(document.querySelectorAll('[data-message-author-role], [data-testid^="conversation-turn-"], article, main [class*="group"], .markdown')):"gemini"===n&&(i=Array.from(document.querySelectorAll('user-query, model-response, message-content, .conversation-container [class*="query"], .conversation-container [class*="response"]'))),i.length||(i=Array.from(document.querySelectorAll('main article, main [role="article"], main .markdown, main p')).slice(-100));const r=new Set,s=[];return i.forEach((t,e)=>{const i=(t.innerText||t.textContent||"").replace(/\r\n/g,"\n").replace(/[ \t]+$/gm,"").replace(/\n{3,}/g,"\n\n").trim();if(!i||i.length<2)return;const c=function(t){let e=2166136261;for(let n=0;n<t.length;n++)e^=t.charCodeAt(n),e=Math.imul(e,16777619);return(e>>>0).toString(16).padStart(8,"0")}(i),l=function(t,e){const n=(t.getAttribute("data-message-author-role")||t.getAttribute("aria-label")||t.getAttribute("data-testid")||t.className||"").toString().toLowerCase();return n.includes("user")||n.includes("you")||n.includes("human")?"user":n.includes("assistant")||n.includes("model")||n.includes("chatgpt")||n.includes("gemini")||n.includes("bot")?"assistant":e%2==0?"user":"assistant"}(t,e),u=`${n}:${o}:${l}:${c}`;r.has(u)||(r.add(u),s.push({platform:n,conversationId:o,conversationTitle:a,role:l,content:i,contentHash:c,messageKey:u,exportedAt:(new Date).toISOString()}))}),{platform:n,conversationId:o,title:a,url:t,messages:s}}

  function detectProviderState(){function p(t){const e=String(t||location.href||location.hostname||"").toLowerCase(),n=location.hostname.toLowerCase();return/127\.0\.0\.1:\d+\/lab\/mock-gemini\.html/i.test(e)?"gemini":/127\.0\.0\.1:\d+\/lab\/mock-chatgpt\.html/i.test(e)?"chatgpt":e.includes("gemini.google.com/app")||n==="gemini.google.com"?"gemini":e.includes("chatgpt.com")||e.includes("chat.openai.com")||e.includes("chat.openai.chatgpt.com")||n.includes("chatgpt.com")?"chatgpt":providerFromUrl(e)}function h(t){let e=2166136261;const n=String(t||"");for(let t=0;t<n.length;t++)e^=n.charCodeAt(t),e=Math.imul(e,16777619);return(e>>>0).toString(16).padStart(8,"0")}const t=p(location.href),n=s=>String(s||"").replace(/\s+/g," ").trim(),a=document.querySelector("textarea"),o=[...document.querySelectorAll('[contenteditable="true"]')],i=o.find(t=>t.getAttribute("role")==="textbox")||o[0]||null,r=n(a?.value||i?.innerText||i?.textContent||""),s=document.body?.innerText||"",c=t==="chatgpt"?!!document.querySelector('button[aria-label*="Stop" i], button[data-testid*="stop" i], [data-testid*="stop"]'):t==="gemini"?!!document.querySelector('button[aria-label*="Stop" i], button[mattooltip*="Stop" i], [aria-label*="Dừng" i]'):/(stop generating|stop response|dừng tạo)/i.test(s),l=!!document.querySelector('[aria-busy="true"], [role="progressbar"], .loader, .spinner'),u=__resolveHelper("extractLatestResponseInPage",extractLatestResponseInPage)("latest"),d=n(u?.content||""),b=n(s),m=`${document.title||""} ${b}`.toLowerCase();let g="conversation";return/chatgpt/.test(t)&&!d&&/log in|sign up|đăng nhập|đăng ký miễn phí/.test(m)&&(g="signin"),/gemini/.test(t)&&/chúng ta nên bắt đầu từ đâu|meet gemini|trò chuyện với gemini|sign in|đăng nhập/.test(m)&&!d&&(g="home"),/chờ một chút|just a moment|cloudflare|turnstile|verify you are human|checking your browser/.test(m)&&(g="interstitial"),{provider:t,isGenerating:c||l,inputDraft:r,latestContent:d,latestHash:d?h(d):null,bodyText:b,bodyHash:b?h(b):null,surface:g}}

  function latestResponseContainsStopPhrase(t){const e=__resolveHelper("extractLatestResponseInPage",extractLatestResponseInPage)("latest");if(!e?.content)return!1;const a=extractQualitySignals(e.content);if(!0===a.shouldContinue)return!1;const n=String(e.content).trim().split(/\r?\n/).map(t=>t.trim()).filter(Boolean);return!!n.length&&n[n.length-1]===String(t).trim()}

  function latestResponseTerminalReady(t){const e=__resolveHelper("extractLatestResponseInPage",extractLatestResponseInPage)("latest");if(!e?.content)return{ok:!1};const a=extractQualitySignals(e.content),n=String(e.content).trim().split(/\r?\n/).map(t=>t.trim()).filter(Boolean),o=!!n.length&&n[n.length-1]===String(t).trim();return{ok:o&&!0!==a.shouldContinue,stopPhrase:o,signals:a,content:e.content}}

  function smokeDetectInPage(){const t=__resolveHelper("detectProviderState",detectProviderState)(),e=__resolveHelper("extractLatestResponseInPage",extractLatestResponseInPage)("latest"),n=(e?.content||"").trim(),a=n.split(/\r?\n/).filter(Boolean).slice(-3),o=["rich-textarea .ql-editor",'.ql-editor[contenteditable="true"]','div[contenteditable="true"][role="textbox"]','div[contenteditable="true"][data-testid*="prompt" i]','textarea','[role="textbox"]',"div.ProseMirror"],i=['button[data-testid="send-button"]','button[data-testid*="send" i]','button[aria-label*="Send" i]','button[aria-label*="Gửi" i]','button[aria-label*="Submit" i]'];return{provider:t?.provider||"unknown",isGenerating:!!t?.isGenerating,inputDraftChars:Number(t?.inputDraft?.length||0),latestChars:n.length,latestTail:a,composerSelectors:o.filter(t=>{try{return!!document.querySelector(t)}catch(e){return!1}}),sendSelectors:i.filter(t=>{try{return!!document.querySelector(t)}catch(e){return!1}}),url:location.href,title:document.title}}

  function countAssistantMessagesInPage(){try{const a=document.querySelectorAll('[data-message-author-role="assistant"]').length;if(a>0)return a;const g=document.querySelectorAll('model-response').length;if(g>0)return g;const c=document.querySelectorAll('[data-testid^="conversation-turn-"]').length;return Math.floor(c/2)}catch(e){return 0}}
  window.__vsbrainPageHelpers = {
    extractQualitySignals,
    providerFromUrl,
    extractLatestResponseInPage,
    clickSendInPage,
    fillPromptInPage,
    pageScanner,
    detectProviderState,
    latestResponseContainsStopPhrase,
    latestResponseTerminalReady,
    smokeDetectInPage,
    countAssistantMessagesInPage,
    version: 'v0.8.58-page-helpers-bundle'
  };
})();
