async function getCheckpoint(t){const e=`checkpoint:${t.platform}:${t.conversationId}`;return(await chrome.storage.local.get(e))[e]||null}
async function setCheckpoint(t,e){const n=`checkpoint:${t.platform}:${t.conversationId}`,a=e[e.length-1],o={platform:t.platform,conversationId:t.conversationId,lastExportedAt:(new Date).toISOString(),lastSeenMessageKey:a?.messageKey,messageCount:e.length,tailHashes:e.slice(-5).map(t=>t.contentHash)};return await chrome.storage.local.set({[n]:o}),o}
async function filterNew(t){const e=await getCheckpoint(t);if(!e?.lastSeenMessageKey)return t.messages;const n=t.messages.findIndex(t=>t.messageKey===e.lastSeenMessageKey);return n<0?t.messages:t.messages.slice(n+1)}
function safeName(t){return(t||"conversation").toLowerCase().replace(/[^a-z0-9_-]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80)||"conversation"}
function inferDownloadMime(t,e){const n=String(t||"").toLowerCase();return n.endsWith(".jsonl")?"application/octet-stream":n.endsWith(".md")?"text/markdown;charset=utf-8":n.endsWith(".json")?"application/json;charset=utf-8":n.endsWith(".txt")?"text/plain;charset=utf-8":e||"application/octet-stream"}
function toBase64Utf8(t){const e=new TextEncoder().encode(String(t||""));let n="";for(let t=0;t<e.length;t+=32768)n+=String.fromCharCode(...e.subarray(t,t+32768));return btoa(n)}
async function downloadText(t,e,n,a=!0){const o=inferDownloadMime(t,n),i=window.__vsbrainActionJournal,r=i?i.hashText(`${t}:${e.length}:${o}`):"",s=i?await i.createAction({actionType:"export",payloadFingerprint:r,phaseVersion:Number(loopState?.step||0),target:{filename:t,mime:o},retryPolicy:"manual_only",meta:{kind:"download_text"}}):null;if(s?.created&&s.action){await i.acknowledge(s.action.actionId),await i.executing(s.action.actionId)}const c=String(t||"").toLowerCase().endsWith(".jsonl"),l=c?`data:${o};base64,${toBase64Utf8(e)}`:URL.createObjectURL(new Blob([e],{type:o}));try{const e=await chrome.downloads.download({url:l,filename:t,saveAs:a,conflictAction:"uniquify"});log(`download started id=${e} file=${t}`),s?.action&&await i.committed(s.action.actionId,{kind:"download_started",value:String(e)}),c||setTimeout(()=>URL.revokeObjectURL(l),3e4);return{downloadId:e,filename:t,mime:o}}catch(e){throw s?.action&&await i.failedBeforeCommit(s.action.actionId,e?.message||String(e)),e}}
async function downloadBundleZip(t,e,n=!0){const o=inferDownloadMime(t,"application/gzip"),i=window.__vsbrainActionJournal,r=i?i.hashText(`${t}:${JSON.stringify(e).length}:bundle`):"",s=i?await i.createAction({actionType:"export",payloadFingerprint:r,phaseVersion:Number(loopState?.step||0),target:{filename:t,mime:o},retryPolicy:"manual_only",meta:{kind:"download_bundle"}}):null;s?.created&&s.action&&(await i.acknowledge(s.action.actionId),await i.executing(s.action.actionId));const c=new CompressionStream("gzip"),l=new TextEncoder().encode(JSON.stringify(e,null,2)),u=new Blob([l],{type:"application/json;charset=utf-8"}).stream().pipeThrough(c),d=await new Response(u).arrayBuffer(),h=URL.createObjectURL(new Blob([d],{type:o}));try{const e=await chrome.downloads.download({url:h,filename:t,saveAs:n,conflictAction:"uniquify"});log(`bundle download started id=${e} file=${t}`),s?.action&&await i.committed(s.action.actionId,{kind:"bundle_download_started",value:String(e)}),setTimeout(()=>URL.revokeObjectURL(h),3e4);return{downloadId:e,filename:t,mime:o}}catch(e){throw s?.action&&await i.failedBeforeCommit(s.action.actionId,e?.message||String(e)),e}}
function toJsonl(t){return t.map(t=>JSON.stringify(t)).join("\n")+(t.length?"\n":"")}
function toMarkdown(t,e){const n=[`# ${t.title}`,"",`- Provider: ${t.platform}`,`- URL: ${t.url}`,`- Exported: ${(new Date).toISOString()}`,""];for(const t of e)n.push(`## ${t.role}`,"",t.content,"");return n.join("\n")}
function estimateTokens(t){const e=String(t||"");if(!e)return 0;const n=(e.match(/[^\x00-\x7F]/g)||[]).length/Math.max(1,e.length)>.2?2.8:4;return Math.ceil(e.length/n)}
function estimateScanTokens(t){const e=(t?.messages||[]).map(t=>`${t.role}: ${t.content}`).join("\n\n"),n=Math.max(0,Number(estimateTokens(e))||0),a=(t?.messages||[]).slice(-6).map(t=>`${t.role}: ${t.content}`).join("\n\n"),o=Math.max(0,Number(estimateTokens(a))||0),i=128e3,r=n>0?Math.round(n/i*1e3)/10:0,s=o>0?Math.round(o/i*1e3)/10:0,c=Math.abs(r-s),l=n<=0||o<=0?"missing":r>120||s>120||c>=25||n>o*2.5?"unreliable":"ok",u="ok"===l?r:r>0&&r<=120?r:s>0&&s<=120?s:Math.min(99.9,Math.max(r||0,s||0,0));return{chars:e.length,tokens_est:n,local_recent_tokens_est:o,usage_pct_est:u,usage_pct_est_dom:r,usage_pct_est_local:s,estimator_delta_pct:Math.round(10*c)/10,estimator_status:l,confidence:"ok"===l?"medium_visible_chat_estimate":"low_dual_estimator_mismatch"}}
async function persistLoopCheckpoint(t={}){if(!window.__vsbrainRecovery)return null;const e=loopState?{sessionId:loopState.sessionId||null,leaseToken:loopState.leaseToken||null,a:loopState.a||null,b:loopState.b||null,currentSource:loopState.currentSource||null,currentTarget:loopState.currentTarget||null,step:Number(loopState.step||0),maxSteps:Number(loopState.maxSteps||0),delayMs:Number(loopState.delayMs||0),waitMs:Number(loopState.waitMs||0),handoffInProgress:!!loopState.handoffInProgress,lastStopReason:lastStopReason||"unknown",autoSend:!!$("autoSendToggle")?.checked,stopPhrase:$("stopPhrase")?.value||defaultStopPhrase(),phase:"runtime_loop",status:"running"}:null;return window.__vsbrainRecovery.saveCheckpoint({...e,...t})}
function buildSessionSlug(t){const e=new Date,n=`${e.getFullYear()}${String(e.getMonth()+1).padStart(2,"0")}${String(e.getDate()).padStart(2,"0")}-${String(e.getHours()).padStart(2,"0")}${String(e.getMinutes()).padStart(2,"0")}${String(e.getSeconds()).padStart(2,"0")}`,a=safeName(t||"session");return `${n}-${a}`.slice(0,96)}
function currentSessionFolder(){const t=loopState?.saveSessionSlug||window.__vsbrainSaveSessionSlug||"adhoc";return `vs-brain/${t}`}
function withSessionFolder(t){const e=String(t||"").replace(/^\/+/,"");return `${currentSessionFolder()}/${e}`}